# Generated by Django 4.2 on 2023-08-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='barcode_image',
            field=models.ImageField(blank=True, upload_to='barcode_images/'),
        ),
    ]
