# Generated by Django 4.2 on 2023-08-26 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_location_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_upload',
            field=models.FileField(blank=True, null=True, upload_to='exercise_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov'])], verbose_name='Video Upload (Max 20MB)'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Link'),
        ),
    ]
