# Generated by Django 4.2 on 2023-08-29 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_exercise_is_upload_exercise_video_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
