# Generated by Django 4.2 on 2023-08-30 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_location_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationdays',
            name='routines',
        ),
        migrations.AddField(
            model_name='locationdays',
            name='routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.routine'),
            preserve_default=False,
        ),
    ]
