# Generated by Django 4.2 on 2023-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_locationdays_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='thumb_image_tube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Link Thumb'),
        ),
    ]
