# Generated by Django 4.2 on 2023-08-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_exercise_routines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routineexercise',
            old_name='exercise',
            new_name='exercise_routine',
        ),
        migrations.RemoveField(
            model_name='routineexercise',
            name='routine',
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='routine_exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routine_exercise', to='api.routine'),
            preserve_default=False,
        ),
    ]
