# Generated by Django 4.2 on 2023-08-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_exercise_routineexercise_exercise_routine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='exercises',
            new_name='r_exercises',
        ),
    ]
