# Generated by Django 4.2 on 2023-08-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_routineexercise_exercise_routine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='routines',
        ),
    ]
