# Generated by Django 4.2 on 2023-09-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_locationdays_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='managername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
