# Generated by Django 4.2 on 2023-09-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_routineexercise_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
