# Generated by Django 4.2 on 2023-09-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_routine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='barcode_images/'),
            preserve_default=False,
        ),
    ]
