# Generated by Django 4.2 on 2023-10-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_program_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programphase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
