# Generated by Django 4.2 on 2023-10-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_programphase_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='phases',
        ),
    ]
