# Generated by Django 4.2 on 2023-10-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_program_phases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programphase',
            name='routines',
        ),
    ]
