# Generated by Django 4.2 on 2023-10-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_programphase_routines'),
    ]

    operations = [
        migrations.AddField(
            model_name='programphase',
            name='routines',
            field=models.ManyToManyField(related_name='routinesPhases', through='api.ProgramPhaseRoutine', to='api.routine'),
        ),
    ]
