# Generated by Django 4.2 on 2023-10-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_subscription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='location',
        ),
    ]
