# Generated by Django 4.2 on 2023-10-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_program_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
