# Generated by Django 4.2 on 2023-10-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_program_show_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
