# Generated by Django 4.2 on 2023-11-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_subscription_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
