# Generated by Django 4.2 on 2023-11-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='defualt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
